#Reference encrypted variables

user_password: "{{ vault_user_password }}"
api_key: "{{ vault_api_key }}"
db_credentials: "{{ vault_db_credentials }}"
user_name: "{{ username }}"
pass: "{{ password }} "


#refernece dev_vault enviorment variables

github_token: "{{ vault_github_token }}"
ap_key2: "{{ vault_api_key2 }}"


#refernce prod_vault enviorment variables

aws_access_key: "{{ vault_aws_access_key }}"


