---
- hosts: local
  gather_facts: no

  vars_files: #have to implicitly mention the path to these files as the playbook does not know where they are 
    - ../group_vars/all/vars.yml
    - ../group_vars/all/vault.yml


  tasks:
    - name: create a user using encrypted password in vault
      ansible.builtin.user: #user bultin user module to create a new user called Syed and using vault_possword
        name: Taha
        shell: /bin/bash
        password: "{{ user_password }}"


